Initial app fix framework event detection.
- detect app install/update start
- parse appID in both cases

diff --git a/src/steamtricks b/src/steamtricks
--- a/src/steamtricks
+++ b/src/steamtricks
@@ -16,6 +16,8 @@ STEAM_RUNTIME=$STEAM_DIR/ubuntu12_32/steam-runtime
 # config defaults
 C_NOTIFICATION=1
 C_NOTIFICATION_CLEAN=1
+C_NOTIFICATION_FIX_APPLY=1
+C_NOTIFICATION_FIX_FETCH=1
 C_STEAM_STARTUP_MAX=120
 
 _C_VERSION=20161003
@@ -35,6 +37,16 @@ strip_quotes()
   clean="${clean%\"}"
   clean="${clean#\"}"
   echo "$clean"
+}
+
+steamtricks_fix_fetch()
+{
+  notify FIX_FETCH "fetching fix for app $1"
+}
+
+steamtricks_fix_apply()
+{
+  notify FIX_APPLY "applying fix for app $1"
 }
 
 # Many apps also ship a libstdc that causes issues in the same way the steam
@@ -87,8 +99,20 @@ steam_content_log_watch()
 
   tail --pid $(pgrep -xo steam) -fn0 "$STEAM_DIR/logs/content_log.txt" | \
   while read line ; do
-    echo "$line" | grep "update changed : None"
+    # steam prints CRLF into log files (issue #4646)
+    # for some reason this does not work when chained above
+    line=$(echo "$line" | tr -d '\r')
+
+    echo "$line" | grep "state changed : Update Required,$" > /dev/null
     if [ $? = 0 ] ; then
+      local parts=($line)
+      steamtricks_fix_fetch ${parts[3]}
+    fi
+
+    echo "$line" | grep "state changed : Fully Installed,$" > /dev/null
+    if [ $? = 0 ] ; then
+      local parts=($line)
+      steamtricks_fix_apply ${parts[3]}
       steam_library_directories_clean
     fi
   done
