Check for failure to enter app_dir.
Applying the fix outside of the app_dir is not only undesired, but a
potential problem given that it may alter non-app files.

diff --git a/src/steamtricks b/src/steamtricks
--- a/src/steamtricks
+++ b/src/steamtricks
@@ -129,6 +129,10 @@ steamtricks_fix_apply()
   if [ -d "$data_dir" ] ; then
     echo "found $data_dir..."
     cd $app_dir
+    if [ ! $? -eq 0 ] ; then
+      echo "unable to enter app_dir"
+      return 1
+    fi
 
     if [ -f "$data_dir/pre" ] ; then
       echo "executing $data_dir/pre"
